apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pyblog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pyblog
    spec:
      containers:
      - name: pyblog
        image: bannastre/pyblog:v0.1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pyblog
  labels:
    app: pyblog
spec:
  type: NodePort
  ports:
   - port: 3000
     targetPort: 8000
  selector:
   app: pyblog