apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyblog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pyblog
    spec:
      containers:
      - name: pyblog
        image: bannastre/pyblog:v0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pyblog
  labels:
    app: pyblog
spec:
  type: LoadBalancer
  ports:
   - port: 8080
     targetPort: 8081
     nodePort: 3000
  selector:
   app: pyblog